# Generated by Django 4.0.3 on 2022-03-18 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('content', models.TextField()),
                ('created_at', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('email', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=64)),
                ('last_login', models.TimeField(default=None)),
                ('created_at', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Votes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('up', models.BooleanField()),
                ('created_at', models.TimeField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feddit.posts')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feddit.users')),
            ],
        ),
        migrations.AddField(
            model_name='posts',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feddit.users'),
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.TimeField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feddit.posts')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feddit.users')),
            ],
        ),
    ]
